apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  namespace: nt548-lab02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: nt548/orders-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: nt548-lab02
spec:
  selector:
    app: orders-service
  ports:
    - port: 8000
      targetPort: 8000
